export const selectOptions = {
    experience: [
        { value: 1, label: 1 },
        { value: 2, label: 2 },
        { value: 3, label: 3 },
        { value: 4, label: 4 },
        { value: 5, label: 5 },
        { value: 6, label: 6 },
        { value: 7, label: 7 },
        { value: 8, label: 8 },
        { value: 9, label: 9 },
        { value: 10, label: 10 },
    ],
    location: [
        { value: 'delhi ncr', label: 'Delhi' },
        { value: 'mumbai', label: 'Mumbai' },
        { value: 'bangalore', label: 'Bangalore' },
        { value: 'hyderabad', label: 'Hyderabad' },
        { value: 'chennai', label: 'Chennai' },
        { value: 'pune', label: 'Pune' },
        { value: 'kolkata', label: 'Kolkata' },
        { value: 'ahmedabad', label: 'Ahmedabad' },
        { value: 'jaipur', label: 'Jaipur' },
        { value: 'surat', label: 'Surat' },
        { value: 'lucknow', label: 'Lucknow' },
        { value: 'kanpur', label: 'Kanpur' },
        { value: 'nagpur', label: 'Nagpur' },
        { value: 'patna', label: 'Patna' },
        { value: 'indore', label: 'Indore' },
        { value: 'thane', label: 'Thane' },
        { value: 'bhopal', label: 'Bhopal' },
        { value: 'visakhapatnam', label: 'Visakhapatnam' },
        { value: 'vadodara', label: 'Vadodara' },
        { value: 'firozabad', label: 'Firozabad' },
        { value: 'ludhiana', label: 'Ludhiana' },
        { value: 'rajkot', label: 'Rajkot' },
        { value: 'agra', label: 'Agra' },
        { value: 'siliguri', label: 'Siliguri' },
        { value: 'nashik', label: 'Nashik' },
        { value: 'faridabad', label: 'Faridabad' },
        { value: 'patiala', label: 'Patiala' },
        { value: 'meerut', label: 'Meerut' },
        { value: 'kalyan-dombivali', label: 'Kalyan-Dombivali' },
        { value: 'vasai-virar', label: 'Vasai-Virar' },
        { value: 'varanasi', label: 'Varanasi' },
        { value: 'srinagar', label: 'Srinagar' },
        { value: 'dhanbad', label: 'Dhanbad' },
        { value: 'jodhpur', label: 'Jodhpur' },
        { value: 'amritsar', label: 'Amritsar' },
        { value: 'madurai', label: 'Madurai' },
        { value: 'raipur', label: 'Raipur' },
        { value: 'guwahati', label: 'Guwahati' },
        { value: 'chandigarh', label: 'Chandigarh' },
    ],
    remote: [
        { value: 'remote', label: 'Remote' },
        { value: 'onsite', label: 'Onsite' },
        { value: 'hybrid', label: 'Hybrid' }
    ],
    techStack: [
        { value: 'react', label: 'React' },
        { value: 'angular', label: 'Angular' },
        { value: 'vue', label: 'Vue' },
        { value: 'node', label: 'Node' },
        { value: 'express', label: 'Express' },
        { value: 'django', label: 'Django' },
        { value: 'flask', label: 'Flask' },
        { value: 'laravel', label: 'Laravel' },
        { value: 'spring', label: 'Spring' },
        { value: 'rails', label: 'Rails' },
        { value: 'wordpress', label: 'Wordpress' },
        { value: 'shopify', label: 'Shopify' },
        { value: 'magento', label: 'Magento' },
        { value: 'woocommerce', label: 'WooCommerce' },
        { value: 'prestashop', label: 'PrestaShop' },
        { value: 'bigcommerce', label: 'BigCommerce' },
        { value: 'opencart', label: 'OpenCart' },
        { value: 'oscommerce', label: 'OsCommerce' },
        { value: 'joomla', label: 'Joomla' },
        { value: 'drupal', label: 'Drupal' },
        { value: 'codeigniter', label: 'CodeIgniter' },
        { value: 'cakephp', label: 'CakePHP' },
        { value: 'yii', label: 'Yii' },
        { value: 'symfony', label: 'Symfony' },
        { value: 'zend', label: 'Zend' },
        { value: 'asp', label: 'ASP' },
        { value: 'net', label: '.NET' },
        { value: 'csharp', label: 'C#' },
        { value: 'vb', label: 'VB' },
        { value: 'java', label: 'Java' },
        { value: 'python', label: 'Python' },
        { value: 'ruby', label: 'Ruby' },
        { value: 'php', label: 'PHP' },
        { value: 'html', label: 'HTML' },
        { value: 'css', label: 'CSS' },
        { value: 'javascript', label: 'JavaScript' },
    ],
    role: [
        { value: 'frontend', label: 'Frontend' },
        { value: 'backend', label: 'Backend' },
        { value: 'android', label: 'Android' },
        { value: 'ios', label: 'IOS' },
        { value: 'techLead', label: 'Tech Lead' },
    ],
    miniBasePay: [
        { value: '0L', label: '0L' },
        { value: '1L', label: '1L' },
        { value: '2L', label: '2L' },
        { value: '3L', label: '3L' },
        { value: '4L', label: '4L' },
        { value: '5L', label: '5L' },
        { value: '6L', label: '6L' },
        { value: '7L', label: '7L' },
        { value: '8L', label: '8L' },
        { value: '9L', label: '9L' },
        { value: '10L', label: '10L' }
    ]

}