export const selectOptions = {
    experience: [
        { value: 1, label: 1 },
        { value: 2, label: 2 },
        { value: 3, label: 3 },
        { value: 4, label: 4 },
        { value: 5, label: 5 },
        { value: 6, label: 6 },
        { value: 7, label: 7 },
        { value: 8, label: 8 },
        { value: 9, label: 9 },
        { value: 10, label: 10 },
    ],
    location: [
        { value: 'delhi', label: 'Delhi' },
        { value: 'mumbai', label: 'Mumbai' },
        { value: 'bangalore', label: 'Bangalore' },
        { value: 'hyderabad', label: 'Hyderabad' },
        { value: 'chennai', label: 'Chennai' },
        { value: 'pune', label: 'Pune' },
        { value: 'kolkata', label: 'Kolkata' },
        { value: 'ahmedabad', label: 'Ahmedabad' },
        { value: 'jaipur', label: 'Jaipur' },
        { value: 'surat', label: 'Surat' },
        { value: 'lucknow', label: 'Lucknow' },
        { value: 'kanpur', label: 'Kanpur' },
        { value: 'nagpur', label: 'Nagpur' },
        { value: 'patna', label: 'Patna' },
        { value: 'indore', label: 'Indore' },
        { value: 'thane', label: 'Thane' },
        { value: 'bhopal', label: 'Bhopal' },
        { value: 'visakhapatnam', label: 'Visakhapatnam' },
        { value: 'vadodara', label: 'Vadodara' },
        { value: 'firozabad', label: 'Firozabad' },
        { value: 'ludhiana', label: 'Ludhiana' },
        { value: 'rajkot', label: 'Rajkot' },
        { value: 'agra', label: 'Agra' },
        { value: 'siliguri', label: 'Siliguri' },
        { value: 'nashik', label: 'Nashik' },
        { value: 'faridabad', label: 'Faridabad' },
        { value: 'patiala', label: 'Patiala' },
        { value: 'meerut', label: 'Meerut' },
        { value: 'kalyan-dombivali', label: 'Kalyan-Dombivali' },
        { value: 'vasai-virar', label: 'Vasai-Virar' },
        { value: 'varanasi', label: 'Varanasi' },
        { value: 'srinagar', label: 'Srinagar' },
        { value: 'dhanbad', label: 'Dhanbad' },
        { value: 'jodhpur', label: 'Jodhpur' },
        { value: 'amritsar', label: 'Amritsar' },
        { value: 'madurai', label: 'Madurai' },
        { value: 'raipur', label: 'Raipur' },
        { value: 'guwahati', label: 'Guwahati' },
        { value: 'chandigarh', label: 'Chandigarh' },
    ]
}