export const selectOptions = {
    experience: [
        { value: 1, label: 1 },
        { value: 2, label: 2 },
        { value: 3, label: 3 },
        { value: 4, label: 4 },
        { value: 5, label: 5 },
        { value: 6, label: 6 },
        { value: 7, label: 7 },
        { value: 8, label: 8 },
        { value: 9, label: 9 },
        { value: 10, label: 10 },
    ],
    location: [
        { value: 'delhi ncr', label: 'Delhi' },
        { value: 'mumbai', label: 'Mumbai' },
        { value: 'bangalore', label: 'Bangalore' },
        { value: 'hyderabad', label: 'Hyderabad' },
        { value: 'chennai', label: 'Chennai' },
        { value: 'pune', label: 'Pune' },
        { value: 'kolkata', label: 'Kolkata' },
       
    ],
    remote: [
        { value: 'remote', label: 'Remote' },
        { value: '', label: 'Onsite' },
    ],
    techStack: [
        { value: 'react', label: 'React' },
        { value: 'angular', label: 'Angular' },
        { value: 'vue', label: 'Vue' },
        { value: 'node', label: 'Node' },
        { value: 'express', label: 'Express' },
        { value: 'django', label: 'Django' },
        { value: 'flask', label: 'Flask' },
        { value: 'laravel', label: 'Laravel' },
        { value: 'spring', label: 'Spring' },
        { value: 'rails', label: 'Rails' },
        { value: 'wordpress', label: 'Wordpress' },
        { value: 'shopify', label: 'Shopify' },
        { value: 'magento', label: 'Magento' },
        { value: 'woocommerce', label: 'WooCommerce' },
        { value: 'prestashop', label: 'PrestaShop' },
        { value: 'bigcommerce', label: 'BigCommerce' },
        { value: 'opencart', label: 'OpenCart' },
        { value: 'oscommerce', label: 'OsCommerce' },
        { value: 'joomla', label: 'Joomla' },
        { value: 'drupal', label: 'Drupal' },
        { value: 'codeigniter', label: 'CodeIgniter' },
        { value: 'cakephp', label: 'CakePHP' },
        { value: 'yii', label: 'Yii' },
        { value: 'symfony', label: 'Symfony' },
        { value: 'zend', label: 'Zend' },
        { value: 'asp', label: 'ASP' },
        { value: 'net', label: '.NET' },
        { value: 'csharp', label: 'C#' },
        { value: 'vb', label: 'VB' },
        { value: 'java', label: 'Java' },
        { value: 'python', label: 'Python' },
        { value: 'ruby', label: 'Ruby' },
        { value: 'php', label: 'PHP' },
        { value: 'html', label: 'HTML' },
        { value: 'css', label: 'CSS' },
        { value: 'javascript', label: 'JavaScript' },
    ],
    role: [
        { value: 'frontend', label: 'Frontend' },
        { value: 'backend', label: 'Backend' },
        { value: 'android', label: 'Android' },
        { value: 'ios', label: 'IOS' },
        { value: 'tech lead', label: 'Tech Lead' },
    ],
    miniBasePay: [
        { value: 10, label: '10L' },
        { value: 20, label: '20L' },
        { value: 30, label: '30L' },
        { value: 40, label: '40L' },
        { value: 50, label: '50L' },
        { value: 60, label: '60L' },
        { value: 70, label: '70L' },
        { value: 80, label: '80L' },
        { value: 90, label: '90L' },
        { value: 100, label: '100L' }
    ]

}


export const jobSliceInitialState = {
    jobs: [],
    status: 'idle',
    error: null,
    page: 0,
    filters: {
        location: [],
        experience: null,
        remote: [],
        techStack: [],
        role: [],
        minBasePay: null,
        companyName: '',
    },
    noMoreJobs: false,
};